# Generated by Django 2.0.3 on 2018-04-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0006_auto_20180409_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='receiver_no',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='item',
            name='sender_no',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
